export const TASKS_LOAD_TASKS = 'TASKS_LOAD_TASKS';
export const TASKS_ADD_TASK = 'TASKS_ADD_TASK';
export const TASKS_UPDATE_TASK = 'TASKS_UPDATE_TASK';
export const TASKS_DELETE_TASK = 'TASKS_DELETE_TASK';
